### ISSUE TITLE
License set as Declared is not in the package

### ISSUE THREAD

**Issue by capfei** [clearlydefined/crawler#519]
https://clearlydefined.io/definitions/pypi/pypi/-/pillow/9.5.0

After harvesting `pypi/pypi/-/pillow/9.5.0` yesterday, it came back with `CAL-1.0` as the declared license but I could not find this anywhere in the harvested data.
<img width="842" alt="image" src="https://user-images.githubusercontent.com/5489711/231472267-56efc8b0-7ace-4906-8bb5-a63e8cb3bcf5.png">

I checked the previous version, 9.4.0, it looks like it also back as `CAL-1.0` in the harvested data.
https://clearlydefined.io/definitions/pypi/pypi/-/pillow/9.4.0

**Comment by qtomlinson** [comment]
There are two problems identified by this issue:
1. extracting declared license in pypiFetch, 
- in ` _extractLicenseFromClassifiers`, `spdxCorrect("Historical Permission Notice and Disclaimer (HPND)")` returns `CAL-1.0`.
- if `info.license` (HPND) is used first instead, the resulting license from spdxCorrect("HPND") would be correct. 

This is related to the [discussion](https://github.com/clearlydefined/crawler/issues/523)
2. scancode summarizer (in service) should pick up the declared license detected in scancode raw data.

**Comment by qtomlinson** [comment]
> 2. scancode summarizer (in service) should pick up the declared license detected in scancode raw data.

This has been fixed by [Commit](https://github.com/qtomlinson/service/commit/19e5a9a2f21972f582ed4706ba2a9a761c87b4a5).

**Comment by capfei** [comment]
This is still happening: https://clearlydefined.io/definitions/pypi/pypi/-/flake8-isort/6.1.2/6.1.2

![Image](https://github.com/user-attachments/assets/b4153288-5e3a-4e37-a419-a28973648c76)

**Comment by qtomlinson** [comment]
Refer to [registryData_flake8isort.json](https://github.com/user-attachments/files/20401447/registryData_flake8isort.json) for downloaded registry data.

The info.license field contains the full license text. When this text is parsed using spdx-correct, it is identified as CAL-1.0. Meanwhile, the license specified in the classifier is listed as 'GNU General Public License v2 (GPLv2)' which can be parsed to GPL-2.0-only. In this case, the classifier license is more accurate.
